logging:
    pattern:
        console: '%d{yyyy-MMM-dd HH:mm:ss.SSS} [%thread] %highlight(%-5level) %cyan(%logger{15})
            - %msg %n'
spring:
    datasource:
        driver-class-name: org.h2.Driver
        testWhileIdle: true
        url: jdbc:h2:mem:myDb;DB_CLOSE_ON_EXIT=FALSE;MV_STORE=FALSE;MVCC=FALSE
        username: sa
        validationQuery: SELECT 1
    h2:
        console:
            enabled: true
            path: /h2-console
    jpa:
        hibernate:
            ddl-auto: create-drop
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.H2Dialect
        show-sql: true
    profiles:
        active:
          - dev