insert into acter(id, class_name, name, health_points, attack, defence, initiative, main) values(1, 'Hero', 'Pera', 10, 2, 1, 5, true)
insert into acter(id, class_name, name, health_points, attack, defence, initiative, main) values(2, 'Hero', 'Zika', 10, 2, 1, 5, true)
insert into acter(id, class_name, name, health_points, attack, defence, initiative, main) values(3, 'Hero', 'Mika', 10, 2, 1, 5, true)
insert into acter(id, class_name, name, health_points, attack, defence, initiative, main) values(4, 'Troll', 'Zeka', 10, 2, 1, 5, true)
insert into acter(id, class_name, name, health_points, attack, defence, initiative, main) values(5, 'Troll', 'Peka', 10, 2, 1, 5, true)